language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
script:
  - pytest test.py
  - coverage run test.py
  - coverage report
after_success:
  - codecov
deploy:
  provider: s3
  secret_key_id:
    secure: EDtwCuFlT4rB+kbOCOkAhqLcJggeMOG/oYoYmRuMrCg8riO/TzuOgIc4oZDt4RGVfBCY6Kg+gTdIg7olJLrztnUIKKhKlBYVYmsm2QwXq9FlBcPZ8IFfBBM1p/zEizg6IYXPyPWqgWhKO8HcXCineeUWyF+yHeZJufbgn+Jc/Jn+/ST2aIbqZ+Obz3XMIGTgrAxVW8bYyUxbQ0slkGhkkxOOB/Nf8o1ffT2TlnG6qJuCAHD3SeD9khYk16pxWz4C621HoNO7SJObIJkN5J1GftLntKiu9fSsnbjBnrMLFitIvbIaYB6WhOXTWNb1SQTfqIdW5YXHFlbPXULEcRglNjaKoNeeFR3bTCJwIlxSQttYw+VTO6TpXXWF9wmfqVRaJKUAgg/d3BzIfB6Ag4jiqdwuRmHN7l5UZnWGNhjsNQBLsgcrYAQTzer32drlUd4MqaZuLBT3v3HVO+EaWMdoSYqonf7MCTHzwgDs9rC0c9ICs5hBBR9uPA3ooGbqLGUzGkoSywY2wW/iKeyMevY9ycVgn3MUAarkK6nulpjZlsk4RtylUCWcvcNJRhcfqHLAZ0xnQqJgzeo6EkzANMk5+gCGrtlgibRp6i9nadJIhWtOZJb2Epv+F1U5xlz4rNwFti+tfApZQpKp4q4a4LhtwW84ztyk0+y8XRaVmL6udjQ=
  secret_access_key:
    secure: lVEjJC4ah0Z8Nlq5bc1rnwErgjNTejMaQrAkYrH3Boz9upTy8b3nGhWW5ElzXfxhIMv1ufOlnpMOtSK7fe3CeXHSJkY5Fq7kuKeNle9sMKaXGrDX68XM0b0/AAL1bZg1axlcTOnVo9tpxrOq0hNNDl+Md4N2pDB+eFKcR1RVih41JOZal4GCiy6Dx3zpYbOAR2dGgf8QkZXk6mAVx3LClADZJ075qaVwfjPCP25qJEyIzuxd37QUePS63mKUffhm/PzmznL4UoFkcBMKcjqzxooU9Aa/ps2apZbjyQTRN5MEaB8A+LZEAxwx9Fex/zmsnYcYgsWff8ekviRsM+iYsBaoK/icbSdbiFkkwD72nkU0FzhY10rVfY4mVUOI3xCLL/WK/ZYp60KKFs13q0R/owhjEjwTfz+uML17Cs8/qfobarDC3HPUluRSXAlHs7iWmsjY4p629rGQCK0NsYEK5PEOaK/kHwvyEMIftKCDmfXXJgVIaNpKnDywPVFCxQMZ3jigAjgykvoWqbdteGqIk95QoFVfPYHsVobgqGwrksbyzP/yYothLLLAv6FgIOM1Cd1CRBXs3IM13RCCz5PlE9TXra+/Up3Gtydb97I514EcNVZlLPeAQRYIWUZckC0U3R624N0EXJYyX0KalyVpNmsMCt+lPs4XJ4YJAoRlkf4=
  bucket: "S3 Bucket"